apiVersion: "cluster.kurl.sh/v1beta1"
kind: "Installer"
metadata: 
  name: "kurl-lab"
spec: 
  kubernetes: 
    version: "1.25.x"
    cisCompliance: true
  flannel: 
    version: "0.20.x"
  contour: 
    version: "1.23.x"
  prometheus: 
    version: "0.60.x"
  containerd: 
    version: "1.6.x"
  ekco: 
    version: "latest"
  fluentd: 
    version: "1.7.x"
  certManager: 
    version: "1.9.x"
