---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: platform
spec:
  title: Platform
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers: []
  ports: []
