apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- storageclass.yaml
- upstream/manifests/vanilla/namespace.yaml
- upstream/manifests/vanilla/vsphere-csi-driver.yaml
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: vsphere-csi-controller
    namespace: vmware-system-csi
  spec:
    replicas: 1
