domain: lab.shortrib.net
remote_ovf_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.ova
default_password: ENC[AES256_GCM,data:MTN6i2BuETBn5lf2idehkqhZ+H/HHgixPQ==,iv:Le8jqiW1RgceAX7hBoeDq14eeY8rKdr7n2EKvxzUN4c=,tag:jhqsGOV2qB1u12bBN0MApw==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:17 600 602
management_cluster:
    name: lacewing
    workers: 2
    metallb_cidr: 10.26.0.65/28
node:
    cpus: 3
    memory: 4096
    disk_size: 40
vsphere:
    server: vcenter.lab.shortrib.net
    username: terraform@shortrib.local
    password: ENC[AES256_GCM,data:xSHFvcWAOWT5G0AZWNMrjxrOpA==,iv:0csgC4bKSCQ+i4UU59wXZA+v8TYfrqHSjjeprpjSANQ=,tag:RvF6/fYTx6hop+1qiRw7QA==,type:str]
    thumbprint: 15:DF:3E:7E:15:A8:CA:5D:BE:9F:B3:46:14:89:7F:99:FB:1B:60:0C
    datacenter: garage
    cluster: homelab
    host: rye.lab.shortrib.net
    resource_pool: homelab/Resources/kurl
    network: kurl-pg
    datastore: vsanDatastore
    folder: replicated
cloudflare:
    api-key: ENC[AES256_GCM,data:z7nGEIIaIW7dbLb9fv638v4dGc3ybT/IFqqzYODLsJ7SOixP/Q==,iv:dFM1u7RcCWqtj3RasGZ6GODYUwNTPugBz2LA+xZu6Mo=,tag:3JLkBQCZIoOJA1o0vx2vvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-01T20:10:54Z"
    mac: ENC[AES256_GCM,data:Fts+/CeliW6wrrOG2T/Mhlr+t+HH1zm3HNoFh+aoTMhMLSSo+8Uu2lwI6RE373yBxlydCadLyHB43bok5i1K+dap6pDaDauhxfkzWC1gw3OFrtE/koh7ilAvZgZbK7ieAtLmyZIWqdGHp6E8rmCJgc+anKzQt2Drbx/XjKHZKn0=,iv:IUST/fJtQXRvQHhRKkWlx8q+13Frg+DMT/aXPGDd1g0=,tag:jo0w32pfNjbSu+ddqeOJEA==,type:str]
    pgp:
        - created_at: "2022-12-26T22:04:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYhYgzaKQYR0SAQdAnEIH6jXaLC20Rtv2DmpFVnFS8V2cGXBoGRWfVN8ZKxMw
            RKNRy+qXH7SOkoe2QY7k1e+WeU8juOwR9ASbumdihAFZzydrrqWRiHf3S+LXcLG9
            0l4Bwf4iz/JEfXGB0HZQKavSATBv4s0/C74TLVidbDP2OaPNciJZZhgX00QpS7eP
            bWQSa/27WXuMQlG7dWPOUqAh7A/yVhgfVMxAKyKp7Byg5a6OhUwzfZK32JoMY7nt
            =KIQj
            -----END PGP MESSAGE-----
          fp: 905EBD494A6AA2B774ED5C67621620CDA290611D
    encrypted_regex: ^(password|api-key|default_password)$
    version: 3.7.3
